[UKI]
PCRPKey=/etc/systemd/tpm2-pcr-public-key.pem
PCRBanks=sha256

[PCRSignature:initrd]
PCRPrivateKey=/etc/systemd/tpm2-pcr-private-key.pem
PCRPublicKey=/etc/systemd/tpm2-pcr-public-key.pem
Phases=enter-initrd
PolicyRef=initrd

[PCRSignature:luks-root]
PCRPrivateKey=/etc/systemd/tpm2-pcr-private-key.pem
PCRPublicKey=/etc/systemd/tpm2-pcr-public-key.pem
Phases=enter-initrd
PolicyRef=luks-root
