[ui]
styleset-name=gruvbox
fuzzy-complete=true
reverse-msglist-order=true
threading-enabled=true
show-thread-context=true

[compose]
address-book-cmd=khard email --remove-first-line --parsable %s
file-picker-cmd=fzf --multi --query=%s
empty-subject-warning=true
no-attachment-warning=^[^>]*attach(ed|ment)

[multipart-converters]
text/html=pandoc -f markdown -t html --standalone

[filters]
text/plain=colorize
text/calendar=calendar
message/delivery-status=colorize
message/rfc822=colorize
text/html=html | colorize
text/*=bat -fP --file-name="$AERC_FILENAME"
application/x-sh=bat -fP -l sh
.headers=colorize

[openers]
x-scheme-handler/http*=librewolf
text/html=librewolf

[hooks]
mail-received=notify-send "[$AERC_ACCOUNT/$AERC_FOLDER] New mail from $AERC_FROM_NAME" "$AERC_SUBJECT"
