---
Index:
  StandardLibrary: Yes
Diagnostics:
  ClangTidy:
    FastCheckFilter: None
  UnusedIncludes: Strict
  # MissingIncludes: Strict
  Includes:
    AnalyzeAngledIncludes: Yes
InlayHints:
  Enabled: Yes
  BlockEnd: Yes
  DefaultArguments: Yes
Hover:
  ShowAKA: Yes
---
If:
  PathMatch: /home/dev/llvm-project/.*
Index:
  External:
    Server: clangd-index.llvm.org:5900
    MountPoint: /home/dev/llvm-project/
