# Keep the unused NvPCR definitions and consumers masked in the initramfs.
FILES+=(
    /etc/nvpcr/cryptsetup.nvpcr
    /etc/nvpcr/hardware.nvpcr
    /etc/nvpcr/login.nvpcr
    /etc/nvpcr/verity.nvpcr
    /etc/systemd/system/systemd-pcrlogin@.service
    /etc/systemd/system/systemd-pcrproduct.service
)
