---
Index:
  StandardLibrary: Yes
Diagnostics:
  ClangTidy:
    FastCheckFilter: None
  UnusedIncludes: Strict
  # MissingIncludes: Strict
  Includes:
    AnalyzeAngledIncludes: Yes
InlayHints:
  Enabled: Yes
  BlockEnd: Yes
  DefaultArguments: Yes
Hover:
  ShowAKA: Yes
# ---
# If:
#   PathMatch: ~/llvm-project/.*
# Index:
#   External:
#     Server: clangd.devel.appentra.com:5900
#     MountPoint: /home/ruifm/work/pw-project
