#!/usr/bin/env sh
# xinitrc file, used by all X sessions started by xinit (startx)
# shellcheck source=/dev/null
[ -r  ~/.config/X11/xprofile ] && . ~/.config/X11/xprofile &
if [ "$(uname -n)" != "tau" ]; then
    exec bspwm
fi
