#!/usr/bin/env sh
# shellcheck source=/dev/null
[ -r  ~/.config/sh/envrc ] && . ~/.config/sh/envrc
display-setup

systemctl --user import-environment PATH DISPLAY XAUTHORITY

[ -r ~/.config/X11/Xresources ] && xrdb ~/.config/X11/Xresources

xsetroot -cursor_name left_ptr &
xset -b
input-setup &
unclutter &
keynav &
if [ "$(uname -n)" != "tau" ]; then
    launch-polybar &
    dunst &
    sxhkd &
fi
