require("guess-indent").setup({})

require("various-textobjs").setup({
  keymaps = {
    useDefaults = true,
  },
})

-- dial.nvim: enhanced increment/decrement on standard vim keys
vim.keymap.set("n", "<C-a>", function()
  return require("dial.map").inc_normal()
end, { expr = true, desc = "Increment" })
vim.keymap.set("n", "<C-x>", function()
  return require("dial.map").dec_normal()
end, { expr = true, desc = "Decrement" })
vim.keymap.set("v", "<C-a>", function()
  return require("dial.map").inc_visual()
end, { expr = true, desc = "Increment" })
vim.keymap.set("v", "<C-x>", function()
  return require("dial.map").dec_visual()
end, { expr = true, desc = "Decrement" })
vim.keymap.set("v", "g<C-a>", function()
  return require("dial.map").inc_gvisual()
end, { expr = true, desc = "Increment (sequential)" })
vim.keymap.set("v", "g<C-x>", function()
  return require("dial.map").dec_gvisual()
end, { expr = true, desc = "Decrement (sequential)" })

-- refactoring.nvim
require("refactoring").setup({})

vim.keymap.set("x", "<leader>re", function()
  require("refactoring").refactor("Extract Function")
end, { desc = "[R]efactor [E]xtract function" })
vim.keymap.set("x", "<leader>rf", function()
  require("refactoring").refactor("Extract Function To File")
end, { desc = "[R]efactor extract function to [F]ile" })
vim.keymap.set("x", "<leader>rv", function()
  require("refactoring").refactor("Extract Variable")
end, { desc = "[R]efactor extract [V]ariable" })
vim.keymap.set("n", "<leader>rI", function()
  require("refactoring").refactor("Inline Function")
end, { desc = "[R]efactor [I]nline function" })
vim.keymap.set({ "x", "n" }, "<leader>ri", function()
  require("refactoring").refactor("Inline Variable")
end, { desc = "[R]efactor [I]nline variable" })
vim.keymap.set("n", "<leader>rb", function()
  require("refactoring").refactor("Extract Block")
end, { desc = "[R]efactor extract [B]lock" })
vim.keymap.set("n", "<leader>rB", function()
  require("refactoring").refactor("Extract Block To File")
end, { desc = "[R]efactor extract [B]lock to file" })
vim.keymap.set("n", "<leader>rp", function()
  require("refactoring").debug.printf({})
end, { desc = "[R]efactor [P]rint" })
vim.keymap.set({ "x", "n" }, "<leader>rV", function()
  require("refactoring").debug.print_var({})
end, { desc = "[R]efactor [P]rint [V]ariable" })
vim.keymap.set("n", "<leader>rc", function()
  require("refactoring").debug.cleanup({})
end, { desc = "[R]efactor [C]leanup" })
